export const SNEAKER_LIST_REQUEST = "SNEAKER_LIST_REQUEST";
export const SNEAKER_LIST_SUCCESS = "SNEAKER_LIST_SUCCESS";
export const SNEAKER_LIST_FAIL = "SNEAKER_LIST_FAIL";

export const SNEAKER_DETAILS_REQUEST = "SNEAKER_DETAILS_REQUEST";
export const SNEAKER_DETAILS_SUCCESS = "SNEAKER_DETAILS_SUCCESS";
export const SNEAKER_DETAILS_FAIL = "SNEAKER_DETAILS_FAIL";
export const SNEAKER_DETAILS_RESET = "SNEAKER_DETAILS_RESET";
